dappx/urls.py
# dappx/urls.py
from django.conf.urls import url
from dappx import views
from django.urls import path
from django.conf.urls.static import static
from dprojx import settings

# SET THE NAMESPACE!
app_name = 'dappx'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^index/$',views.index,name='index'),
    url(r'^details/(?P<product_id>\d+)/$',views.details,name='details'),
    url(r'^search/$', views.search, name='search'),
    url(r'^category/(?P<category_name>.*)/$', views.category, name='category'),
    url(r'^listby/(?P<search_filter>.*)/(?P<filter_t>.*)/(?P<minimum_price>.*)/(?P<maximum_price>.*)/$', views.listby, name='listby'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^password/$', views.change_password, name='change_password'),
    url(r'^account$', views.account, name='account'),
    url(r'^view_orders$', views.view_orders, name='view_orders'),
  	#path(r'^cart/<int:pr_id>/', views.cart, name='cart'),
    #path(r'^cart/', views.cart, name='cart'),
    url(r'^cart/(?P<pr_id>.*)/$', views.cart, name='cart'),
    url(r'^remove_item/(?P<pr_id>.*)/$', views.remove_item, name='remove_item'),
    url(r'^checkout/$',views.checkout,name='checkout'),
    url(r'^checkout_complete/$',views.checkout_complete,name='checkout_complete'),

]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dprojx/urls.py
# dprojx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url #,include
from dappx import views
from django.conf.urls.static import static
from dprojx import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^dappx/',include('dappx.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^details',views.details,name='details'),
    path('<int:product_id>/',views.details,name='details'),
    url(r'^salesmanager',views.salesmanager,name='salesmanager'),
    url(r'^productmanager',views.productmanager,name='productmanager'),
  	#path(r'^cart/<int:pr_id>/', views.cart, name='cart'),
    #path(r'^cart/', views.cart, name='cart'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile/edit$', views.edit_profile, name='edit_profile'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^account$', views.account, name='account'),
    url(r'^cart', views.cart, name='cart'),
    path('<int:pr_id>/', views.cart, name='cart'),
    url(r'^remove_item', views.remove_item, name='remove_item'),
    path('<int:pr_id>/', views.remove_item, name='remove_item'),
    url(r'^checkout/$',views.checkout,name='checkout'),
    url(r'^checkout_complete/$',views.checkout_complete,name='checkout_complete'),

] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

dappx/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from datetime import timedelta
from django.utils import timezone
from django.db.models import Sum

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    #portfolio_site = models.URLField(blank=True)
    #profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    #email =  models.CharField(max_length=100, null=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=20, null=True, blank=True)
    address =  models.CharField(max_length=100, null=True, blank=True)
    city =  models.CharField(max_length=100, null=True, blank=True)
    country = models.CharField(max_length=100, null=True, blank=True)
    

    def __str__(self):
        return self.user.username


class productcategories (models.Model):
    # STATUS = (
    #     (1,'True'),
    #     (0,'False'),
    # )
    CategoryName = models.CharField(max_length=100)

    def __str__(self):
        return self.CategoryName



# Create your models here.
class products (models.Model):
    # STATUS = (
    #     (1,'True'),
    #     (0,'False'),
    # )
    name = models.CharField(max_length=100)
    id = models.AutoField(primary_key=True)
    CategoryID = models.ForeignKey(productcategories,on_delete=models.CASCADE)
    brand = models.CharField(max_length=100)
    price = models.FloatField()
    Quantity = models.CharField(max_length=100)
    ShortDesc = models.CharField(max_length=100)
    LongDesc = models.CharField(max_length=100)
    image=models.ImageField(upload_to= 'foods')
    stock = models.FloatField(max_length=100)
    Location = models.CharField(max_length=100)
    changedprice = models.FloatField()
    commented = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.name



class cartItem(models.Model):
    itemID = models.AutoField(primary_key=True)
    product = models.OneToOneField(products, on_delete=models.SET_NULL, null=True)
    itemquantity = models.IntegerField(default=1)#how much is added to the cart
    date_added = models.DateTimeField(auto_now=True)
    itemPrice = models.FloatField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    totalCost = models.FloatField(max_length=100,default=0)

    def set_itemPrice(self):
        self.itemPrice = (self.itemquantity)*(self.product.changedprice)
        return self.itemPrice

    def get_cart_total(self):
        self.totalCost = sum(self.all().itemPrice)
        return self.totalCost

    def __str__(self):
        return 'cartItem: {}'.format(self.product)




class orders (models.Model):
    orderID = models.AutoField(primary_key=True)
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preparing', 'Preparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
    )
    details = models.ForeignKey(cartItem, null=True, on_delete=models.SET_NULL)
    status = models.CharField(choices=STATUS, max_length=160, default='New')
    date_created = models.DateTimeField(auto_now_add=True)

    def return_date_due():
        now = timezone.now()
        return now + timedelta(days=7)
    
    date_due = models.DateTimeField(default=return_date_due)

    def __str__(self):
        return 'orders: {}'.format(self.details)


class Comment(models.Model):
    STATUS = (
        ('New', 'New'),
        ('True', 'True'),
        ('False', 'False'),
    )
    product = models.ForeignKey(products,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    subject = models.CharField(max_length=50)
    comment = models.CharField(max_length=250)
    rate = models.IntegerField(default=1)
    ip = models.CharField(max_length=20,blank=True)
    status = models.CharField(max_length=10,choices=STATUS,default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.comment

dappx/views.py
from django.shortcuts import render, redirect
from dappx.forms import UserForm,UserProfileInfoForm,UserChangeForm,EditProfileForm, CommentForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash#makes sure that the user is logged in even after redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from dappx.models import products,productcategories,cartItem,orders,UserProfileInfo, Comment
from django.db.models import Q
from django.db import transaction
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.core.mail import send_mail

from django.contrib.messages import constants as messages
from django.db.models import Avg


def index(request):
    return render(request,'dappx/index.html')
@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
def register(request):
    category = productcategories.objects.all()
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        #email = user_form.fields.email()
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
            email = request.POST.get('email')
            send_mail(
    'BringSUya Hoşgeldiniz',
    'Sitemize üye olduğunuz için teşekkürler. ',
    'EMAIL_HOST_USER ',
    [email],)
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render(request,'dappx/registration.html',
                        {'user_form':user_form,
                        'profile_form':profile_form,
                        'registered':registered,
                        'category': category})

def user_login(request):
    category = productcategories.objects.all()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                if (username == 'salesmanager' and password == 'deneme12'):
                    return HttpResponseRedirect(reverse('salesmanager'))
                elif (username == 'productmanager' and password == 'deneme') :
                    return HttpResponseRedirect(reverse('productmanager'))
                else:  
                    return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'dappx/login.html', {'category': category})


def index(request):
    category = productcategories.objects.all()
    product = products.objects.all()
    content = {'category':category, 'product':product}
    # return render (request,'dappx/index.html',{'category': category})
    return render (request,'dappx/index.html',content)



def search(request):
    #if request.method == 'GET':
        query= request.GET.get('q')
        submitbutton= request.GET.get('submit')
        category = productcategories.objects.all()
        if query is not None:
            lookups= Q(name__icontains=query) | Q(brand__icontains=query) | Q(ShortDesc__icontains=query) | Q(LongDesc__icontains=query)
            results= products.objects.filter(lookups).distinct()

            categlookups = Q(CategoryID__CategoryName__icontains=query)
            categresults = products.objects.filter(categlookups).distinct()
            context={'results': results,
                    'submitbutton': submitbutton,
                    'category': category,
                    'categresults': categresults}

            return render(request, 'dappx/search_results.html', context)
        else:
            return render(request, 'dappx/search_results.html', {'category': category} )
    #else:
     #   return render(request, 'dappx/search_results.html')



def category(request, category_name):
    results= products.objects.filter(CategoryID__CategoryName=category_name).distinct()
    specificCateg = productcategories.objects.all().filter(CategoryName=category_name).distinct()
    category = productcategories.objects.all()
    context= {'results': results, 'specificCateg': specificCateg, 'category':category}    
    return render(request, 'dappx/category_results.html', context)






def listby(request, search_filter, filter_t, minimum_price, maximum_price):
    category = productcategories.objects.all()
    filter=search_filter #örn: süt. searchlediğin şey
    f = filter_t

    lookups= Q(name__icontains=search_filter) | Q(brand__icontains=search_filter) | Q(ShortDesc__icontains=search_filter) | Q(LongDesc__icontains=search_filter)
    results= products.objects.filter(lookups).distinct()
    print('results', results)
    categlookups = Q(CategoryID__CategoryName__icontains=search_filter)
    categresults = products.objects.filter(categlookups).distinct()

    min_price = 0
    max_price = 0

    submitbutton = request.GET.get('submit')
 
    #at this step it may 
    #price is submitted from form by filling the boxes
    if minimum_price=="None" and minimum_price=="None":
        min_price = request.GET.get('minprice')
        max_price = request.GET.get('maxprice')
        submitbutton = request.GET.get('submit')
        #if min_price is None and max_price is None and submitbutton=="None":
        if min_price is None and max_price is None:
            
            #no price is entered but listby is wanted by the user
            if filter_t!="None":

                if filter_t=="increasing":
                    results= products.objects.filter(lookups).order_by('changedprice').distinct()
                    categresults = products.objects.filter(categlookups).order_by('changedprice').distinct()
    
                elif filter_t=="decreasing":
                    results= products.objects.filter(lookups).order_by('-changedprice').distinct()
                    categresults = products.objects.filter(categlookups).order_by('-changedprice').distinct()
                
                elif filter_t=="alphabetical":
                    results= products.objects.filter(lookups).order_by('name').distinct()
                    categresults = products.objects.filter(categlookups).order_by('name').distinct()
            
                elif filter_t=="nonalphabetical":
                    results= products.objects.filter(lookups).order_by('-name').distinct()
                    categresults = products.objects.filter(categlookups).order_by('-name').distinct()
                
            context= {'results': results, 'categresults':categresults, 'category':category, 'f':f, 'filter':filter}
            return render(request, 'dappx/listby_results.html', context)
       

        
    #prices are already provided, here we 
    #form is not used, user wanted  to list by
    elif minimum_price is not None and maximum_price is not None:
        print("minimum_price: ", type(minimum_price))
        min_price=float(minimum_price)
        max_price=float(maximum_price)
        
        results = products.objects.filter(lookups, changedprice__range=(min_price, max_price)).distinct()
        categresults = products.objects.filter(categlookups, changedprice__range=(min_price, max_price)).distinct()
        
    #############min, max values are set  until here


    if min_price==max_price:
        #context= {'results': results,  'category':category, 'categresults':categresults, 'submitbutton':submitbutton, 'filter':filter}    
        context = {'category':category}
        return render(request, 'dappx/search_results.html', context) ##will tell there is no result found
        
    else:
        #print("checkminimum price: ", min_price)
        #print("checkmaximum price: ", max_price)
        #print("filter type: ", filter_t)
        #print("price type: ", min_price)
        
        min_price = float(min_price)
        max_price = float(max_price)
        if filter_t=="increasing":
            results= products.objects.filter(lookups, changedprice__range=(min_price, max_price)).order_by('changedprice').distinct()
            categresults = products.objects.filter(categlookups, changedprice__range=(min_price, max_price)).order_by('changedprice').distinct()

        elif filter_t=="decreasing":
            results= products.objects.filter(lookups, changedprice__range=(min_price, max_price)).order_by('-changedprice').distinct()
            categresults = products.objects.filter(categlookups, changedprice__range=(min_price, max_price)).order_by('-changedprice').distinct()
        
        elif filter_t=="alphabetical":
            results= products.objects.filter(lookups, changedprice__range=(min_price, max_price)).order_by('name').distinct()
            categresults = products.objects.filter(categlookups, changedprice__range=(min_price, max_price)).order_by('name').distinct()
    
        elif filter_t=="nonalphabetical":

templates/dappx/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Base</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


    <style>
   body {
  font-family: "Lato", sans-serif;
}

.sidebar {
  height: 100%;
  width: 0;
  position: fixed;
  z-index: 1;
  top: 0;
  left: 0;
  background-color: rgb(4, 48, 18);
  overflow-x: hidden;
  transition: 0.5s;
  padding-top: 60px;
}

.sidebar a {
  padding: 8px 8px 8px 32px;
  text-decoration: none;
  font-size: 25px;
  color: #818181;
  display: block;
  transition: 0.3s;
}

.sidebar a:hover {
  color: #f1f1f1;
}

.sidebar .closebtn {
  position: absolute;
  top: 10px;
  right: 25px;
  font-size: 36px;
  margin-left: 50px;
}

.openbtn {
  font-size: 15px;
  cursor: pointer;
  background-color: #ECEFF1;
  color: rgb(13, 133, 53);
  padding: 10px 15px;
  border: none;
}

.openbtn:hover {
  background-color:rgb(186, 198, 206);
}

#main {
  transition: margin-left .5s;
  padding: 5px;
}

/* On smaller screens, where height is less than 450px, change the style of the sidenav (less padding and a smaller font size) */
@media screen and (max-height: 450px) {
  .sidebar {padding-top: 15px;}
  .sidebar a {font-size: 18px;}
}
    .main {
      margin-left: 160px; /* Same as the width of the sidenav */
      font-size: 28px; /* Increased text to enable scrolling */
      padding: 0px 10px;
    }
    .ex1 {
      padding-top: 2.5%;
      }

      .button {
  background-color: #ddd;
  border: none;
  color: black;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;
  cursor: pointer;
  border-radius: 16px;
}  
    
    @media screen and (max-height: 450px) {
      .sidenav {padding-top: 15px;}
      .sidenav a {font-size: 18px;}
    }
    div.a {
    width: 200px;
    }
      
    #myBtn {
      display: none; /* Hidden by default */
      position: fixed; /* Fixed/sticky position */
      bottom: 20px; /* Place the button at the bottom of the page */
      right: 30px; /* Place the button 30px from the right */
      z-index: 99; /* Make sure it does not overlap */
      border: none; /* Remove borders */
      outline: none; /* Remove outline */
      background-color:#d9534f ; /* Set a background color */
      color: white; /* Text color */
      cursor: pointer; /* Add a mouse pointer on hover */
      padding: 15px; /* Some padding */
      border-radius: 10px; /* Rounded corners */
      font-size: 18px; /* Increase font size */
    }

    #myBtn:hover {
      background-color: #a6ce7e; /* Add a dark-grey background on hover */
    }


    </style>
</head>
<body>    
  <nav class="navbar navbar-light" style="background-color: #ECEFF1;  " >
    <div class="container">
      <div class="topnav">
        <ul class="nav navbar-nav">
        <li>

         
        <div id="mySidebar" class="sidebar">
          {% for CategoryName in category%}
          <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">×</a>
          <a class="dropdown-item" href="{% url 'dappx:category' category_name=CategoryName %}">{{ CategoryName }}</a>
          {% endfor %}
        </div>

        <div id="main">
          <button class="openbtn" onclick="openNav()"><i class="fa fa-align-justify"></i> Kategoriler</button>  
        
        </div>

        <script>
        function openNav() {
          document.getElementById("mySidebar").style.width = "200px";
          document.getElementById("main").style.marginLeft = "250px";
        }

        function closeNav() {
          document.getElementById("mySidebar").style.width = "0";
          document.getElementById("main").style.marginLeft= "0";
        }
        </script>
      </li>

      
    
        
         
          <!--li><a class="navbar-brand fa fa-home w3-large"href="{% url 'index' %}"></a></li--->
          <li><a class="button" href="{% url 'index' %}" style="width: 50px; height:40px; text-align: center; background: url('/static/image/1284_600_b.jpg') no-repeat; background-size: 100%; opacity: 1;" >             </a></li>
            
          <li>
            <form class="form-inline ml-auto ex1" action="{% url 'dappx:search' %}" method="GET" value="{{request.GET.q}}">
              <input  type="text" name="q" value="{{request.GET.q}}" class="form-control mr-sm-2 ex1"   placeholder="Search...">
              <input type="submit" class="btn btn-outline-light ex1" name="submit" value="Search"/>
          <!--<a><button type="submit" class="btn btn-outline-light" method="get">Search</button></a-->
            </form>
           
        </li>
        
        
      	
        
      </ul>


        <ul class="nav navbar-nav navbar-right" >
          <li><a class="navbar-link"  style ="color:rgb(13, 133, 53);" href="{% url 'dappx:cart' pr_id=-1 %}" ><i class="fa fa-shopping-cart w3-large" style ="color:rgb(13, 133, 53);"></i>Sepetim</a></li>
          {# Some logic on what to display for last item#}
          {% if user.is_authenticated %}
              <li><a href="{% url 'account' %}" style ="color:rgb(13, 133, 53);"><i class="glyphicon glyphicon-user"></i>Hello, {{user.username}}</a></li>
              <li><a href="{% url 'logout' %}" style ="color:rgb(13, 133, 53);"><i class="fa fa-sign-out"  style ="color:rgb(13, 133, 53);"></i>Logout</a></li>
              {% else %}
              <li><a class="navbar-link"  style ="color:rgb(13, 133, 53);" href="{% url 'admin:index' %}" style ="color:rgb(13, 133, 53);">Admin</a></li>
              <li><a class="navbar-link" style ="color:rgb(13, 133, 53);" href="{% url 'dappx:register' %}"><span class="glyphicon glyphicon-user"  style ="color:rgb(13, 133, 53);"></span>Register</a></li>     
              <li><a class="navbar-link"  style ="color:rgb(13, 133, 53);" href="{% url 'dappx:user_login' %}"><span class="glyphicon glyphicon-log-in" style ="color:rgb(13, 133, 53);"></span></i>Login</a></li>
          {% endif %}

        </ul>
          
    </div>
    </nav>
    <div class="container">
    {% block body_block %}
    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
     <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

templates/dappx/cart.html
{% extends "dappx/base.html" %}
{% block body_block %}
<style>
    .row {
  display: -ms-flexbox; /* IE10 */
  display: flex;
  -ms-flex-wrap: wrap; /* IE10 */
  flex-wrap: wrap;
  margin: 0 -16px;
}

.col-25 {
  -ms-flex: 25%; /* IE10 */
  flex: 25%;
}

.col-50 {
  -ms-flex: 50%; /* IE10 */
  flex: 50%;
}

.col-75 {
  -ms-flex: 75%; /* IE10 */
  flex: 75%;
}

.col-25,
.col-50,
.col-75 {
  padding: 0 16px;
}

 .container1 {
  background-color: #f2f2f2;
 padding: 5px 20px 15px 20px; 
  border: 1px solid lightgrey;
  border-radius: 3px;
  margin-left: 145px;
} 
.container2 {
  background-color: #f2f2f2;
 padding: 5px 20px 15px 20px; 
  border: 1px solid lightgrey;
  border-radius: 3px;
} 

input[type=text] {
  width: 100%;
  margin-bottom: 20px;
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 3px;
}

label {
  margin-bottom: 10px;
  display: block;
}

.icon-container {
  margin-bottom: 20px;
  padding: 7px 0;
  font-size: 24px;
}

.checkoutbtn {
  background-color: #4CAF50;
  color: white;
  padding: 12px;
  margin: 10px 0;
  border: none;
  width: 100%;
  border-radius: 3px;
  cursor: pointer;
  font-size: 17px;
}

.checkoutbt:hover {
  background-color: #45a049;
}

span.price {
  float: right;
  color: grey;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other (and change the direction - make the "cart" column go on top) */
@media (max-width: 800px) {
  .row {
    flex-direction: column-reverse;
  }
  .col-25 {
    margin-bottom: 20px;
  }
}
</style>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <div class="col-25">
      <div class="container2">
        <h4>Sepetim
          <span class="price" style="color:black">
            <i class="fa fa-shopping-cart"></i>
            {% if cartProducts  %}
            <b >{{cartProducts.length}}</b>
            {% endif %} 
          </span>
        </h4>
        {% if cartProducts  %}

        {% for cpr in cartProducts %} 
 
        <p><a>{{cpr.product.name}}  {{cpr.itemquantity}} x {{cpr.itemPrice}} TL</a> <span class="price">{{cpr.totalCost}} tl</span><form method='GET' action="{% url 'dappx:remove_item' pr_id=cpr.itemID %}"><button class="btn btn-danger mt-3" type="submit" >Kaldır</button></form></p>
        <!-- <button style="float: center;">Kaldır</button> -->
        
        {% endfor %}


        <hr>
        {% if tcost > 0 %}
        <p>Toplam <span class="price" style="color:black"><b>{{tcost|floatformat:2}} tl</b></span></p>
        {% endif %} 
        
        {% else %}
        <p style="text-align:center">Alışveriş Sepetiniz Boş</p>
        <p style="text-align:center">Biraz gezinmeye ne dersin?</p>
        <p style="text-align:center"><a class="button" href="{% url 'dappx:index' %}">Alışverişe Başla</a></p>
        {% endif %} 

      </div>
    </div>
    <br>
    <label>Ödeme tipi : </label>
    <label style="text-indent: 45px;">
      <form method="GET">
        <input type="radio"  name="creditcart"> Kredi Kartı
        <input type="radio"  name="cash" style="margin-left: 40px;"> Nakit / Kapıda Ödeme
      </form>
    </label>
    <br>
    <label>
      <input type="checkbox" checked="checked" name="sameadr"> Teslimat adresi ve fatura adresi aynı
    </label>
    <form  action="{% url 'dappx:checkout' %}"><button class="checkoutbtn">Ödeme Yap</button></form>
  </form>
  <!-- </div>  -->

<!-- </div> -->
{% endblock %}